const insultsArray = [
    "If brains were dynamite, you couldn't blow your nose.",
    "You're the human equivalent of a participation award.",
    "Somewhere out there, a tree is tirelessly producing oxygen so you can breathe. I think you owe it an apology.",
    "You have the charm and emotional depth of a concrete slab.",
    "You're like the end pieces of a loaf of bread. Everyone touches you, but nobody wants you.",
    "If ignorance is bliss, you must be living in paradise.",
    "You're the reason the gene pool needs a lifeguard.",
    "Your birth certificate is an apology letter from the condom factory.",
    "You're as useful as a screen door on a submarine.",
    "You have all the appeal of a paper cut.",
    "Your IQ test results came back negative.",
    "You're as irrelevant as the 'Skip Intro' button on a show's best episode.",
    "You're the reason we have warning labels on shampoo bottles.",
    "You're like a software update. When I see you, I think 'Not now.'",
    "Your family tree must be a cactus because everybody on it is a prick.",
    "You're about as useful as a knitted condom.",
    "You're the human embodiment of a Monday.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "You're as pointless as a white crayon.",
    "You're the audio version of a headache.",
    "You're like a slinky; not really good for much, but you bring a smile to my face when pushed down the stairs.",
    "You're the top search result for 'how to waste oxygen.'",
    "Your code is so buggy, it qualifies as a new habitat for endangered species.",
    "You're the reason the mute button was invented.",
    "You're as welcome as a fart in an elevator.",
    "Your personality is so bland, it's the vegan option of human interaction.",
    "If you were a vegetable, you'd be a cabba-don't.",
    "You're like a typo in a love letter.",
    "You're the human version of a typo.",
    "You're like the first slice of bread; everyone touches you, but no one wants you.",
    "If stupidity was a profession, you'd be a mogul.",
    "You're the diet soda of evil. Just not sinister enough.",
    "You're as mysterious as a public restroom with no toilet paper.",
    "You're the 'Terms and Conditions' of people. Everyone knows you're there but nobody cares.",
    "You're like an expired coupon, utterly disappointing.",
    "You're the pebble in the shoe of humanity.",
    "You're as significant as a drop of water in the ocean.",
    "Your presence is like finding a raisin in a cookie when you expected chocolate chip.",
    "You're the human equivalent of a participation trophy.",
    "You're like a glitch in the matrix, but less cool and more annoying."
  ];

const jokesArray = [
    "Why did the developer break up with his girlfriend? She couldn't handle his recursive love.",
    "Why don't algorithms ever get lost? Because they always follow their GPS (General Problem Solver).",
    "Why was the HTML file sad? It had too many tags but no one to <header> with.",
    "Why did the SQL query go to therapy? It had too many relationship issues.",
    "Why did the computer go to the doctor? Because it had a virus and needed a byte.",
    "Why did the AI break up with its neural network? It felt like it was being overtrained.",
    "Why did the programmer go to art class? To learn how to draw circles in JavaScript.",
    "Why was the JavaScript developer sad? Because he lost all his classes and couldn't find them in the DOM.",
    "Why don't programmers like to play hide and seek? Because good luck hiding when you're always in plain sight (of the compiler).",
    "Why did the programmer bring a ladder to the bar? Because he heard the drinks were on the house.",
    "Why was the programmer cold at night? He forgot to close his while loop.",
    "Why was the function feeling insecure? Because it had too many parameters and felt like it wasn't being called enough.",
    "Why was the HTML file lonely? It had no body to share its content with.",
    "Why was the computer cold? It left its browser open all night.",
    "Why did the developer go broke? He spent all his money on software subscriptions.",
    "Why did the programmer get stuck in the shower? Because he couldn't find the soap (source) code.",
    "Why did the JavaScript code always win at poker? Because it could bluff with promises.",
    "Why did the developer break up with his girlfriend? She couldn't handle his recursive love.",
    "Why don't algorithms ever get lost? Because they always follow their GPS (General Problem Solver).",
    "Why was the HTML file sad? It had too many tags but no one to <header> with.",
    "Why did the SQL query go to therapy? It had too many relationship issues.",
    "Why did the computer go to the doctor? Because it had a virus and needed a byte.",
    "Why did the AI break up with its neural network? It felt like it was being overtrained.",
    "Why did the programmer go to art class? To learn how to draw circles in JavaScript.",
    "Why was the JavaScript developer sad? Because he lost all his classes and couldn't find them in the DOM.",
    "Why don't programmers like to play hide and seek? Because good luck hiding when you're always in plain sight (of the compiler).",
    "Why did the programmer bring a ladder to the bar? Because he heard the drinks were on the house.",
    "Why was the programmer cold at night? He forgot to close his while loop.",
    "Why was the function feeling insecure? Because it had too many parameters and felt like it wasn't being called enough.",
    "Why was the HTML file lonely? It had no body to share its content with.",
    "Why was the computer cold? It left its browser open all night.",
    "Why did the developer go broke? He spent all his money on software subscriptions.",
    "Why did the programmer get stuck in the shower? Because he couldn't find the soap (source) code.",
    "Why did the JavaScript code always win at poker? Because it could bluff with promises.",
    "Why don't programmers play hide and seek with AI? Because it always finds them by the first iteration.",
];


  export default insultsArray jokesArray;
