const insultsArray = [
    "If brains were dynamite, you couldn't blow your nose.",
    "You're the human equivalent of a participation award.",
    "Somewhere out there, a tree is tirelessly producing oxygen so you can breathe. I think you owe it an apology.",
    "You have the charm and emotional depth of a concrete slab.",
    "You're like the end pieces of a loaf of bread. Everyone touches you, but nobody wants you.",
    "If ignorance is bliss, you must be living in paradise.",
    "You're the reason the gene pool needs a lifeguard.",
    "Your birth certificate is an apology letter from the condom factory.",
    "You're as useful as a screen door on a submarine.",
    "You have all the appeal of a paper cut.",
    "Your IQ test results came back negative.",
    "You're as irrelevant as the 'Skip Intro' button on a show's best episode.",
    "You're the reason we have warning labels on shampoo bottles.",
    "You're like a software update. When I see you, I think 'Not now.'",
    "Your family tree must be a cactus because everybody on it is a prick.",
    "You're about as useful as a knitted condom.",
    "You're the human embodiment of a Monday.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "You're as pointless as a white crayon.",
    "You're the audio version of a headache.",
    "You're like a slinky; not really good for much, but you bring a smile to my face when pushed down the stairs.",
    "You're the top search result for 'how to waste oxygen.'",
    "Your code is so buggy, it qualifies as a new habitat for endangered species.",
    "You're the reason the mute button was invented.",
    "You're as welcome as a fart in an elevator.",
    "Your personality is so bland, it's the vegan option of human interaction.",
    "If you were a vegetable, you'd be a cabba-don't.",
    "You're like a typo in a love letter.",
    "You're the human version of a typo.",
    "You're like the first slice of bread; everyone touches you, but no one wants you.",
    "If stupidity was a profession, you'd be a mogul.",
    "You're the diet soda of evil. Just not sinister enough.",
    "You're as mysterious as a public restroom with no toilet paper.",
    "You're the 'Terms and Conditions' of people. Everyone knows you're there but nobody cares.",
    "You're like an expired coupon, utterly disappointing.",
    "You're the pebble in the shoe of humanity.",
    "You're as significant as a drop of water in the ocean.",
    "Your presence is like finding a raisin in a cookie when you expected chocolate chip.",
    "You're the human equivalent of a participation trophy.",
    "You're like a glitch in the matrix, but less cool and more annoying."
  ];

  export default insultsArray;